int_libs = # interface dependencies.
imp_libs = # implementation dependencies.

lib{bitmagic}: {hxx ixx txx}{** -version} hxx{version} $imp_libs $int_libs

# include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base"

# export options.
#
lib{bitmagic}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base"
  cxx.export.libs = $int_libs
}

# install into the libbitmagic/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libbitmagic/
  install.subdirs = true
}
